# Generated by Django 4.2.15 on 2024-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_departments', models.PositiveIntegerField(default=0)),
                ('number_of_employees', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
